# Generated by Django 5.2 on 2025-04-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_patientrecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='user',
        ),
    ]
