# Generated by Django 5.2 on 2025-04-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_patientrecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorfee',
            name='total_fee',
        ),
        migrations.AddField(
            model_name='doctorfee',
            name='fee',
            field=models.IntegerField(default=0),
        ),
    ]
