# Generated by Django 5.2 on 2025-04-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_doctorfee_total_fee_doctorfee_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=30),
        ),
    ]
